### ISSUE TITLE
[Schedule page] Message ''Disconnected Wrong access token'' should be more informative

### ISSUE THREAD

**Issue by atishevich** [gem-platform/gem#104]
Pre-conditions:
Role "1" is created with enabled only 'Manage meeting' checkbox
Meeting is created and role 1 doesn't include to this meeting

Steps:
Login to system as user with role 1
Press Start button on meeting

AR: Disconnected Wrong access token  - error is displaeyd 
ER: More informative message is displayed
 
Note: the same message when user press on button Join!!!!

**Comment by akdasa** [comment]
![image](https://user-images.githubusercontent.com/22368151/46136689-e500b080-c250-11e8-8967-d282adf85c82.png)

Done
