### ISSUE TITLE
[Dashboard][Proposal] It is should be impossible to create proposal without data

### ISSUE THREAD

**Issue by atishevich** [gem-platform/gem#26]
Steps:

1. Go to Proposal page
2. Press Create new button
3. Press Save button

AR: Proposal is created
ER: Proposal isn't created because no data was entered , validation icons are displayed
![4-26-2018 11-27-22 am](https://user-images.githubusercontent.com/38349881/39294902-94eba5d4-4945-11e8-8c23-780148a7094c.jpg)

**Comment by atishevich** [comment]
Note! It is should be impossible to create role, user without data

**Comment by akdasa** [comment]
Now it displays "Validation error" popup. To make it more user-frendly see #156 For further development.
