### ISSUE TITLE
[Dashsboard][Proposals] Exclamation mark icons should have the same size 

### ISSUE THREAD

**Issue by atishevich** [gem-platform/gem#27]
Steps:
Go to proposal page
Press Create button
Press Save button ->Exclamation mark icons are appeared
Check Exclamation mark icons size 

AR: Exclamation mark icons have different
![4-26-2018 11-35-42 am](https://user-images.githubusercontent.com/38349881/39295439-1d693056-4947-11e8-9cc2-2bd4fb6981a5.jpg)
 size 
ER: Exclamation mark icons should have the same size

**Comment by akdasa** [comment]
They are of different sizes: Index, Title are the **main** fields, that's why they are bigger.

<img width="1458" alt="2018-09-27 11 49 34" src="https://user-images.githubusercontent.com/22368151/46134394-6d7c5280-c24b-11e8-90b1-9d90c79b7d1f.png">
