### ISSUE TITLE
[Dashboard] Created meeting, user, role should be displayed in readable view 

### ISSUE THREAD

**Issue by atishevich** [gem-platform/gem#33]
Select any created meeting , user , role
Check the view
AR: Created meeting, user, role isn't 
![4-27-2018 3-53-41 pm](https://user-images.githubusercontent.com/38349881/39363664-bc9dc7c6-4a33-11e8-90cc-cb998e9733ed.jpg)
![4-27-2018 3-54-04 pm](https://user-images.githubusercontent.com/38349881/39363668-bec4baaa-4a33-11e8-930f-c86af3786d78.jpg)
![4-27-2018 3-54-16 pm](https://user-images.githubusercontent.com/38349881/39363670-c04cfcca-4a33-11e8-9d85-f1d622faaf2d.jpg)

displayed in readable view 
ER: Created meeting, user, role should be displayed in readable view

**Comment by akdasa** [comment]
Done.
