### ISSUE TITLE
[Meetings] User couldn't add proposal in saved meeting 

### ISSUE THREAD

**Issue by atishevich** [gem-platform/gem#57]
Login as superuser
Create new meeting
Fill in required values
Proposal field user doesn't fill in
Save meeting
Edit just created meeting
Check proposal field

AR: proposal field is empty 

ER: user fills in proposal's field

**Comment by atishevich** [comment]
![6-22-2018 6-29-38 pm](https://user-images.githubusercontent.com/38349881/41785129-491f7888-764a-11e8-8831-7f6ddc4a93be.jpg)

**Comment by atishevich** [comment]
vendor.16725964e188e98d3874.js:2 TypeError: Cannot read property 'toString' of undefined
    at Object.contains (index.f79ed0643ef528453549.js:1)
    at index.f79ed0643ef528453549.js:1
    at Array.filter (<anonymous>)
    at a.searchResults (index.f79ed0643ef528453549.js:1)
    at Ae.get (vendor.16725964e188e98d3874.js:2)
    at Ae.evaluate (vendor.16725964e188e98d3874.js:2)
    at a.searchResults (vendor.16725964e188e98d3874.js:2)
    at a.r (index.f79ed0643ef528453549.js:1)
    at a.t._render (vendor.16725964e188e98d3874.js:2)
    at a.<anonymous> (vendor.16725964e188e98d3874.js:2)
zt @ vendor.16725964e188e98d3874.js:2

**Comment by atishevich** [comment]
browser-polyfill.js:610 Uncaught (in promise) {message: "Could not establish connection. Receiving end does not exist."}
callbackArgs @ browser-polyfill.js:610
sendResponseAndClearCallback @ VM848 extensions::messaging:417
disconnectListener @ VM848 extensions::messaging:435
EventImpl.dispatchToListener @ VM841 extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ VM847 extensions::utils:138
EventImpl.dispatch_ @ VM841 extensions::event_bindings:387
EventImpl.dispatch @ VM841 extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ VM847 extensions::utils:138
dispatchOnDisconnect @ VM848 extensions::messaging:378

**Comment by akdasa** [comment]
Cause: Proposal with no title (undefined)

**Comment by akdasa** [comment]
Fixed. Issue was in incorrect data, what no longer can be added with validation.
