### ISSUE TITLE
[Login page] Errors in console are displayed at Login page 

### ISSUE THREAD

**Issue by atishevich** [gem-platform/gem#7]
Go to login page http://stage.gem.iskcon.org/login
Check console

AR:
xhr.js:178 GET http://stage.gem.iskcon.org/api/auth/user 401 (UNAUTHORIZED)
plugin.js:26 [ERROR] [AUTH] Error: Request failed with status code 401
    at createError (createError.js:16)
    at settle (settle.js:18)
    at XMLHttpRequest.handleLoad (xhr.js:77)

socket.js:9 Uncaught TypeError: Cannot read property 'dispatch' of undefined
    at Vue.disconnect (socket.js:9)
    at build.js:1
    at Array.forEach (<anonymous>)
    at t.value (build.js:1)
    at r.<anonymous> (build.js:1)
    at r.emit (build.js:1)
    at r.emit (build.js:1)
    at r.onclose (build.js:1)
    at r.<anonymous> (build.js:1)
    at r.emit (build.js:1)
﻿

​ER: No errrors are displayed

**Comment by akdasa** [comment]
ER: ```/api/auth/user``` should not be called before user authorization.

```
# Authenticate first
POST http://localhost/api/auth/login 200 (OK)

# When fetch user data
GET http://stage.gem.iskcon.org/api/auth/user 200 (OK)
```

**Comment by akdasa** [comment]
Some errors are still present, but it seems that they [can not be avoided](https://stackoverflow.com/questions/16372271/jquery-ajax-how-to-prevent-404-errors-spam-in-chrome-devtools). However, 401 for /api/auth/login is OK.

![image](https://user-images.githubusercontent.com/22368151/38770547-3c4b960e-401d-11e8-9d31-4d5cc78ee70b.png)

**Comment by atishevich** [comment]
passed. closed
